name: Build and publish to Docker Hub

on:
- push
- release
push:
  branches:
  - master
release:
  tags:
  - v*

jobs:
  build:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image with tag
      run: docker build --tag ${GITHUB_REPOSITORY}:${DOCKER_IMAGE_TAG} .
      env:
        DOCKER_IMAGE_TAG: ${{ format(github.ref, 'master', 'latest') }}
    - name: Login to Docker Registry
      run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} -
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${GITHUB_REPOSITORY}:${DOCKER_IMAGE_TAG}
      env:
        DOCKER_IMAGE_TAG: ${{ format(github.ref, 'master', 'latest') }}
