name: Build and publish to DockerHub

on:
  push:
    branches:
    - master
  release:
    tags:
    - v*

jobs:
  build:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image with tag
      run: docker build --tag ${GITHUB_REPOSITORY}:latest .
      if: github.event_name == 'push'
    - name: Build docker image with tag
      run: docker build --tag ${GITHUB_REPOSITORY}:${{ github.ref }} .
      if: github.event_name == 'release'
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push to DockerHub
      run: docker push ${GITHUB_REPOSITORY}:${{ github.latest }}
      if: github.event_name == 'push'
    - name: Push to DockerHub
      run: docker push ${GITHUB_REPOSITORY}:${{ github.ref }}
      if: github.event_name == 'release'
    - name: Logout from DockerHub
      run: docker logout
